model:
  base_learning_rate: 4.5e-6
  target: lidm.models.ae.autoencoder_object.VQModel_Object
  params:
    monitor: val/rec_loss
    embed_dim: 1024
    n_embed: 4096
    lib_name: lidm
    use_mask: False  # False
    lossconfig:
      target: lidm.modules.losses.vqperceptual.VQGeoLPIPSWithDiscriminator1D
      params:
        disc_conditional: false

    modelconfig:
      target: lidm.modules.encoders.object_encoder.G2SD
      params:
        z_channels: 1024
        num_grids: 256

data:
  target: train_lidm.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 8
    wrap: true
    dataset:
      size: [64, 1024]
    aug:
      flip: true
    train:
      target: lidm.data.nuscenes_object_detaset.NuscenesObject
      params:
        data_root: /home/alan/AlanLiang/Dataset/pcdet_Nuscenes/v1.0-trainval
        pkl_path: /home/alan/AlanLiang/Dataset/pcdet_Nuscenes/v1.0-trainval/nuscenes_dbinfos_10sweeps_withvelo.pkl
        # data_root: /mnt/scratch/e/e1493786/AlanLiang/Dataset/Nuscenes/v1.0-trainval
        # pkl_path: /mnt/scratch/e/e1493786/AlanLiang/Dataset/Nuscenes/v1.0-trainval/nuscenes_dbinfos_10sweeps_withvelo.pkl

        split: train

    validation:
      target: lidm.data.nuscenes_object_detaset.NuscenesObject
      params:
        data_root: /home/alan/AlanLiang/Dataset/pcdet_Nuscenes/v1.0-trainval
        pkl_path: /home/alan/AlanLiang/Dataset/pcdet_Nuscenes/v1.0-trainval/nuscenes_dbinfos_10sweeps_withvelo.pkl
        # data_root: /mnt/scratch/e/e1493786/AlanLiang/Dataset/Nuscenes/v1.0-trainval
        # pkl_path: /mnt/scratch/e/e1493786/AlanLiang/Dataset/Nuscenes/v1.0-trainval/nuscenes_dbinfos_10sweeps_withvelo.pkl
        split: val

lightning:

  trainer:
    benchmark: true
    accumulate_grad_batches: 2
