model:
  base_learning_rate: 1.0e-06
  target: lidm.models.diffusion.ddpm.LayoutDiffusion
  params:
    linear_start: 0.0001
    linear_end: 0.02
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    channels: 8
    monitor: val/loss_simple_ema
    # condition
    cond_stage_key: scene_graph
    conditioning_key: 'graph_crossattn'
    cond_stage_trainable: true
    verbose: false

    unet_config:
      target: lidm.modules.unets.unet_1d.UNet1DModel
      params:
        dims: 1
        in_channels: 8 # size(3)+loc(3)+sincos(2)
        out_channels: 8 # same
        model_channels: 512
        channel_mult: [ 1,1,1,1]
        num_res_blocks: 2
        attention_resolutions: [ 4, 2 ]
        num_heads: 8
        # cond_model params
        use_spatial_transformer: true
        transformer_depth: 1
        conditioning_key: 'crossattn'
        concat_dim: 1280
        crossattn_dim: 1280
        use_checkpoint: true
        enable_t_emb: true

    cond_stage_config: # TODO
      target: lidm.modules.encoders.scene_graph.SceneGraph
      params:
        embedding_dim: 64
        gconv_pooling: 'avg'
        gconv_num_layers: 5
        mlp_normalization: 'batch'
        separated: true
        replace_latent: true
        residual: true
        use_angles: true
        use_clip: true

data:
  target: train_layout.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 8
    wrap: true
    dataset:
      size: [64, 1024]
      fov: [ 3,-25 ]
      depth_range: [ 1.0,56.0 ]
      depth_scale: 5.84  # np.log2(depth_max + 1)
      log_scale: true
      x_range: [ -50.0, 50.0 ]
      y_range: [ -50.0, 50.0 ]
      z_range: [ -3.0, 1.0 ]
      resolution: 1
      num_channels: 1
      num_cats: 10
      num_views: 2
      num_sem_cats: 19
      filtered_map_cats: [ ]
    aug:
      flip: true
      rotate: false
      keypoint_drop: false
      keypoint_drop_range: [ 5,20 ]
      randaug: false
    train:
      target: lidm.data.nuscenes_layout_dataset.nuScenesLayoutTrain
      params:
        root: /home/alan/AlanLiang/Projects/AlanLiang/CentralScene/data/nuscenes
        shuffle_objs: true
        use_scene_rels: true
        with_changes: false
        eval: false
        with_CLIP: true
        bin_angle: false
        seed: false
        recompute_feats: false
        recompute_clip: false
        
    validation:
      target: lidm.data.nuscenes_layout_dataset.nuScenesLayoutVal
      params:
        root: /home/alan/AlanLiang/Projects/AlanLiang/CentralScene/data/nuscenes
        use_scene_rels: true
        with_changes: false
        eval: true
        with_CLIP: true
        bin_angle: false

lightning:

  trainer:
    benchmark: true